In [1]:
import torch

In [2]:
batch_size = 4
window_size = 3
neg_count = 5
dim = 10
center_idx = 3

In [3]:
S = torch.arange(batch_size * (2 * window_size + 1) * dim).reshape(batch_size, 
                                                                   2 * window_size + 1, 
                                                                   dim)
S

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],

        [[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]],

        [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 

In [4]:
center_words = S[:, center_idx, :].unsqueeze(1)
center_words, center_words.shape

(tensor([[[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]],
 
         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109]],
 
         [[170, 171, 172, 173, 174, 175, 176, 177, 178, 179]],
 
         [[240, 241, 242, 243, 244, 245, 246, 247, 248, 249]]]),
 torch.Size([4, 1, 10]))

In [5]:
context_mask = torch.ones(S.shape[1])
context_mask = context_mask.type(torch.ByteTensor)
context_mask[center_idx] = 0
context_mask, context_mask.shape

(tensor([1, 1, 1, 0, 1, 1, 1], dtype=torch.uint8), torch.Size([7]))

In [6]:
pos_contexts = S[:, context_mask, :]
pos_contexts, pos_contexts.shape

(tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
          [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
          [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],
 
         [[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
          [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
          [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
          [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]],
 
         [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
          [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
          [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
          [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
  

In [7]:
pos_dots = torch.bmm(center_words, pos_contexts.transpose(1, 2))
pos_dots, pos_dots.shape

(tensor([[[  1635,   5085,   8535,  15435,  18885,  22335]],
 
         [[ 77935,  88385,  98835, 119735, 130185, 140635]],
 
         [[252235, 269685, 287135, 322035, 339485, 356935]],
 
         [[524535, 548985, 573435, 622335, 646785, 671235]]]),
 torch.Size([4, 1, 6]))

In [8]:
S

tensor([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],

        [[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139]],

        [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 

In [10]:
neg_contexts = S[:, center_idx, :]
neg_contexts, neg_contexts.shape

(tensor([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
         [240, 241, 242, 243, 244, 245, 246, 247, 248, 249]]),
 torch.Size([4, 10]))

In [12]:
neg_idx = torch.randint(neg_contexts.shape[0], size = (batch_size, neg_count))
neg_idx, neg_idx.shape

(tensor([[1, 3, 1, 1, 1],
         [1, 2, 1, 0, 3],
         [3, 0, 1, 0, 0],
         [1, 1, 1, 0, 1]]), torch.Size([4, 5]))

In [11]:
neg_samples = neg_contexts[neg_idx]
neg_samples, neg_samples.shape

(tensor([[[240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
          [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
          [170, 171, 172, 173, 174, 175, 176, 177, 178, 179]],
 
         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
          [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
          [240, 241, 242, 243, 244, 245, 246, 247, 248, 249]],
 
         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
          [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
          [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [170, 171, 172, 173, 174, 175, 176, 177, 178, 179]],
 
         [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],

In [12]:
center_words.shape

torch.Size([4, 1, 10])

In [13]:
torch.bmm(center_words, neg_samples.transpose(1, 2))

tensor([[[ 84435,  11985,  36135,  60285,  60285]],

        [[109285, 255585, 182435,  36135, 255585]],

        [[182435, 426735, 426735, 182435, 304585]],

        [[255585, 426735, 426735,  84435, 426735]]])

In [29]:
torch.randint(high=S.shape[0], size=(S.shape[0], ))

tensor([2, 3, 2, 3])

In [35]:
window_samples = S[torch.randint(high=S.shape[0], size=(S.shape[0], )), :, :]
window_samples

tensor([[[210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
         [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
         [230, 231, 232, 233, 234, 235, 236, 237, 238, 239],
         [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
         [250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
         [260, 261, 262, 263, 264, 265, 266, 267, 268, 269],
         [270, 271, 272, 273, 274, 275, 276, 277, 278, 279]],

        [[140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
         [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
         [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
         [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
         [200, 201, 202, 203, 204, 205, 206, 207, 208, 209]],

        [[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91, 

In [ ]:
neg_idx = [[3, 0, 1, 2, 2],
          [1, 3, 2, 0, 3],
          [1, 3, 3, 1, 2],
          [1, 2, 2, 0, 2]]

neg_idx = [[3, 0], [1, 3], [1, 3], [1, 2]]
window_samples.index_select(dim=0, neg_idx)